# Generated by Django 3.2.16 on 2025-01-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250109_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'categorys', 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'default_related_name': 'locations', 'verbose_name': 'местоположение', 'verbose_name_plural': 'Местоположения'},
        ),
    ]
