# Generated by Django 3.2.16 on 2025-02-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
